from setuptools import setup, find_packages

setup(
    name="catastrophic-forgetting-research",
    version="0.1.0",
    description="Research framework for exploring catastrophic forgetting in neural networks",
    author="Research Team",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.24.0",
        "matplotlib>=3.6.0",
        "seaborn>=0.12.0",
        "pandas>=2.0.0",
        "scikit-learn>=1.3.0",
        "jupyter>=1.0.0",
        "notebook>=6.5.0",
        "tensorboard>=2.13.0",
        "tqdm>=4.65.0",
        "plotly>=5.15.0",
        "scipy>=1.10.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)